service: 
  name: keepitclean-backend-nodejs

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-sequelize-migrations

custom:
  region: us-east-1
  stage: dev
  stackPrefix: ${opt:stackPrefix, 'keep-it-clean'}
  baseStack: ${opt:stackPrefix, 'keep-it-clean'}-${opt:stage, 'dev'}-base-infra

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    DB_DIALECT: mysql
    DB_PORT: 3306
    DB_HOST: ${cf:${self:custom.baseStack}.RDSHost}
    DB_NAME: database_master
    DATABASE: database_master
    DB_USERNAME: db_user
    DB_PASSWORD: testpass
    USER_POOLID: ${cf:${self:custom.baseStack}.UserPoolId}
    CLIENT_ID: ${cf:${self:custom.baseStack}.UserPoolClientId}

functions:
  
  create: 
    handler: src/api/user.create
    events:
      - http:
          path: api/user
          method: post
          cors: true
          integration: lambda

resources:
  - ${file(./serverless-assets/serverless-template.yml)}
