insert into UsaLocalLaw (code,state,reference) values ('AL','Alabama','http://adem.alabama.gov/alEnviroRegLaws/default.cnt');
insert into UsaLocalLaw (code,state,reference) values ('AK','Alaska','https://dec.alaska.gov/eh/solid-waste/how-do-i-dispose-of/');
insert into UsaLocalLaw (code,state,reference) values ('AZ','Arizona','https://azdeq.gov/recycling');
insert into UsaLocalLaw (code,state,reference) values ('AR','Arkansas','https://www.adeq.state.ar.us/regs/');
insert into UsaLocalLaw (code,state,reference) values ('CA','California','https://www.calrecycle.ca.gov/reducewaste/packaging/lawsregs#');
insert into UsaLocalLaw (code,state,reference) values ('CO','Colorado','https://cdphe.colorado.gov/recycling');
insert into UsaLocalLaw (code,state,reference) values ('CT','Connecticut','https://portal.ct.gov/DEEP/Reduce-Reuse-Recycle/Recycling-Regulations-and-Statutes');
insert into UsaLocalLaw (code,state,reference) values ('DE','Delaware','https://dnrec.alpha.delaware.gov/waste-hazardous/recycling/#');
insert into UsaLocalLaw (code,state,reference) values ('FL','Florida','https://floridadep.gov/waste/waste-reduction/content/florida-recycling-statutes-and-rules#');
insert into UsaLocalLaw (code,state,reference) values ('GA','Georgia','https://www.dca.ga.gov/local-government-assistance/planning/local-planning/solid-waste-management-recycling-assistance');
insert into UsaLocalLaw (code,state,reference) values ('HI','Hawaii','https://portal.ehawaii.gov/residents/recycling-and-waste/');
insert into UsaLocalLaw (code,state,reference) values ('ID','Idaho','https://www.deq.idaho.gov/waste-management-and-remediation/solid-waste/recycling-reuse-and-composting/');
insert into UsaLocalLaw (code,state,reference) values ('IL','Illinois','https://www2.illinois.gov/cms/agency/recycling/Pages/default.aspx');
insert into UsaLocalLaw (code,state,reference) values ('IN','Indiana','https://www.in.gov/idem/recycle/');
insert into UsaLocalLaw (code,state,reference) values ('IA','Iowa','https://www.iowadnr.gov/environmental-protection/land-quality/solid-waste/solid-waste-policy-rules');
insert into UsaLocalLaw (code,state,reference) values ('KS','Kansas','https://www.kdheks.gov/waste/p_regsandstatutes.html');
insert into UsaLocalLaw (code,state,reference) values ('KY','Kentucky','https://eec.ky.gov/Environmental-Protection/Waste/recycling-and-local-assistance/recycling/Pages/default.aspx');
insert into UsaLocalLaw (code,state,reference) values ('LA','Louisiana','https://deq.louisiana.gov/page/recycling');
insert into UsaLocalLaw (code,state,reference) values ('ME','Maine','http://maine.gov/dep/waste/recycle/');
insert into UsaLocalLaw (code,state,reference) values ('MD','Maryland','https://mde.maryland.gov/programs/land/recyclingandoperationsprogram/pages/recylingrates.aspx');
insert into UsaLocalLaw (code,state,reference) values ('MA','Massachusetts','https://www.mass.gov/service-details/waste-recycling-laws-rules');
insert into UsaLocalLaw (code,state,reference) values ('MI','Michigan','https://www.michigan.gov/egle/0,9429,7-135-3312-385337--,00.html');
insert into UsaLocalLaw (code,state,reference) values ('MN','Minnesota','https://mn.gov/admin/government/buildings-grounds/building-management/recycling/');
insert into UsaLocalLaw (code,state,reference) values ('MS','Mississippi','https://www.mdeq.ms.gov/about-mdeq/regulations/');
insert into UsaLocalLaw (code,state,reference) values ('MO','Missouri','https://dnr.mo.gov/waste.htm');
insert into UsaLocalLaw (code,state,reference) values ('MT','Montana','http://deq.mt.gov/land/recycle');
insert into UsaLocalLaw (code,state,reference) values ('NE','Nebraska','https://das.nebraska.gov/materiel/recycling/why-recycle.html');
insert into UsaLocalLaw (code,state,reference) values ('NV','Nevada','https://ndep.nv.gov/land/waste/statutes-and-regulations');
insert into UsaLocalLaw (code,state,reference) values ('NH','New Hampshire','https://www.des.nh.gov/waste');
insert into UsaLocalLaw (code,state,reference) values ('NJ','New Jersey','https://www.nj.gov/dep/dshw/recycling/');
insert into UsaLocalLaw (code,state,reference) values ('NM','New Mexico','https://www.env.nm.gov/solid-waste/rules-and-statutes/');
insert into UsaLocalLaw (code,state,reference) values ('NY','New York','https://www.dec.ny.gov/chemical/294.html#');
insert into UsaLocalLaw (code,state,reference) values ('NC','North Carolina','https://deq.nc.gov/conservation/recycling/state-agencies/general-recycling-requirements-and-banned-materials');
insert into UsaLocalLaw (code,state,reference) values ('ND','North Dakota','https://deq.nd.gov/WM/Recycling/');
insert into UsaLocalLaw (code,state,reference) values ('OH','Ohio','https://www.epa.ohio.gov/ocapp/recycling');
insert into UsaLocalLaw (code,state,reference) values ('OK','Oklahoma','https://www.deq.ok.gov/land-protection-division/recycling/recycling-information/');
insert into UsaLocalLaw (code,state,reference) values ('OR','Oregon',"https://www.oregon.gov/deq/recycling/Pages/Oregon's-Recycling-Laws.aspx#");
insert into UsaLocalLaw (code,state,reference) values ('PA','Pennsylvania','https://www.dep.pa.gov/Business/Land/Waste/Recycling/Pages/default.aspx');
insert into UsaLocalLaw (code,state,reference) values ('RI','Rhode Island','https://www.rirrc.org/recycling-composting-disposal/what-to-recycle-in-your-bin-cart');
insert into UsaLocalLaw (code,state,reference) values ('SC','South Carolina','https://scdhec.gov/environment/recycling-waste-reduction/state-agency-recycling-responsibilities');
insert into UsaLocalLaw (code,state,reference) values ('SD','South Dakota','https://denr.sd.gov/des/wm/recycle/recycleguide.aspx');
insert into UsaLocalLaw (code,state,reference) values ('TN','Tennessee','https://www.tn.gov/health/cedep/environmental/healthy-schools/hs/recycling-program.html');
insert into UsaLocalLaw (code,state,reference) values ('TX','Texas','https://www.tceq.texas.gov/permitting/waste_permits/msw_permits/MSW_amIregulatedrecycling.html');
insert into UsaLocalLaw (code,state,reference) values ('UT','Utah','https://deq.utah.gov/waste-management-and-radiation-control/recycling-waste-reduction-reuse-program');
insert into UsaLocalLaw (code,state,reference) values ('VT','Vermont','https://dec.vermont.gov/waste-management/solid/universal-recycling');
insert into UsaLocalLaw (code,state,reference) values ('VA','Virginia','https://law.lis.virginia.gov/admincode/title9/agency20/chapter130/section125/');
insert into UsaLocalLaw (code,state,reference) values ('WA','Washington','https://ecology.wa.gov/Waste-Toxics/Reducing-recycling-waste');
insert into UsaLocalLaw (code,state,reference) values ('WV','West Virginia','https://dep.wv.gov/WWE/Programs/solidwaste');
insert into UsaLocalLaw (code,state,reference) values ('WI','Wisconsin','https://dnr.wisconsin.gov/topic/Recycling/law.html');
insert into UsaLocalLaw (code,state,reference) values ('WY','Wyoming','http://deq.wyoming.gov/shwd/solid-waste/resources/rules-regs/?no_redirect=true');