Resources:
  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      ProviderARNs: 
        - ${cf:${self:custom.baseStack}.UserPoolArn}

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub ${stackPrefix}-${stage}-userpool
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Schema:
        - Name: first_name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: last_name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: user_name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: false
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub ${stackPrefix}-client
      GenerateSecret: false
      UserPoolId: !Ref UserPool

Output:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  UserPoolArn:
    Value:
      Fn::GetAtt:
        - UserPool
        - Arn